apiVersion: v1
kind: ServiceAccount
metadata:
  name: alina-1-rollout-reporter-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alina-1-rollout-reporter-role
rules:
- apiGroups:
  - argoproj.io
  resources:
  - analysisruns
  - rollouts
  verbs:
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alina-1-rollout-reporter-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alina-1-rollout-reporter-role
subjects:
- kind: ServiceAccount
  namespace: codefresh
  name: alina-1-rollout-reporter-sa

---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: alina-1-rollout-reporter
  labels:
    app.kubernetes.io/managed-by: cf
spec:
  eventBusName: codefresh-eventbus
  resource:
    analysisruns:
      cluster: alina-1
      group: argoproj.io
      version: v1alpha1
      resource: analysisruns
      eventTypes:
      - ADD
      - UPDATE
      - DELETE
    replicasets:
      cluster: alina-1
      group: apps
      version: v1
      resource: replicasets
      eventTypes:
      - ADD
      - UPDATE
      - DELETE
    rollouts:
      cluster: alina-1
      group: argoproj.io
      version: v1alpha1
      resource: rollouts
      eventTypes:
      - ADD
      - UPDATE
      - DELETE
  template:
    serviceAccountName: alina-1-rollout-reporter-sa

---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: alina-1-rollout-reporter
  labels:
    app.kubernetes.io/managed-by: cf
spec:
  dependencies:
  - name: analysisruns
    eventSourceName: alina-1-rollout-reporter
    eventName: analysisruns
  - name: replicasets
    eventSourceName: alina-1-rollout-reporter
    eventName: replicasets
  - name: rollouts
    eventSourceName: alina-1-rollout-reporter
    eventName: rollouts
  eventBusName: codefresh-eventbus
  template:
    serviceAccountName: alina-1-rollout-reporter-sa
  triggers:
  - template:
      name: rollouts
      conditions: rollouts
      http:
        method: POST
        url: https://hermes-onprem-test.cf-op.com/2.0/api/events
        headers:
          Content-Type: application/json
        secureHeaders:
        - name: Authorization
          valueFrom:
            secretKeyRef:
              key: token
              name: codefresh-token
        payload:
        - dest: data.object
          src:
            dataKey: body
            dependencyName: rollouts
    retryStrategy:
      duration: 0
      steps: 3
  - template:
      name: replicasets
      conditions: replicasets
      http:
        method: POST
        url: https://hermes-onprem-test.cf-op.com/2.0/api/events
        headers:
          Content-Type: application/json
        secureHeaders:
        - name: Authorization
          valueFrom:
            secretKeyRef:
              key: token
              name: codefresh-token
        payload:
        - dest: data.object
          src:
            dataKey: body
            dependencyName: replicasets
    retryStrategy:
      duration: 0
      steps: 3
  - template:
      name: analysisruns
      conditions: analysisruns
      http:
        method: POST
        url: https://hermes-onprem-test.cf-op.com/2.0/api/events
        headers:
          Content-Type: application/json
        secureHeaders:
        - name: Authorization
          valueFrom:
            secretKeyRef:
              key: token
              name: codefresh-token
        payload:
        - dest: data.object
          src:
            dataKey: body
            dependencyName: analysisruns
    retryStrategy:
      duration: 0
      steps: 3
