kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: docker
  creationTimestamp: null
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  labels:
    codefresh.io/entity: integration-secret
    codefresh.io/integration-name: docker
    codefresh.io/integration-type: registry.dockerhub
spec:
  template:
    metadata:
      name: docker
      creationTimestamp: null
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
  encryptedData:
    password: >-
      AgAzH0/CaOFHRDfnNrS7S3zWNt3tw52pFEtTGZo0AhNX+4+6gGtbv/QcVx6JnmhY7641d9lEZEfzbhJmEdX8oL3HDSP9hEUTDhSpJkzuOYXTkUzSz2wzXTnkrGivBxGIfD/1y6qEHYskV73csISOY+ISbn3MNZmFA54OSO7gzKfUn1kB69CDWODEgO9eGhSl0zWBomfNiUOv4J4I+EVF7HEhJ9mIMHjzTu2fOUDdtXXyhYsYDIQEThjBora2/62/o68Ox4rT/6f+0RRcmaf4sJ5aiIEGBZqiZWHxo1k854IggwoFZEZ9yHX/Afx+M4wCuSQNbg8ajzaT9Hxz5YAHm3UJBew9IfAFTEEVAsMISDu7uZXjMhSp7PaXwex0qach52/JXdekgTGrivlMAEi44OeCgqut+/+gb7oRtGdeVMhkw5wTX0VdWwWgKl6x6BtmxO3xD8G5iEAJgxC+za+1EwZRLgNISNCPnUu5NG0h55tFIAcHe+bpRJy4Hxlw0ZULbsk5IHwfW+0iZ1eOjjgYDIwfBUK1OZEApASiWCHGqPnFFVhSUMQeZLMVJBTfOrdaRnz2gJRYMSIf0m3+ITPDlEus1l9fuKhwysLwyTOvfDKBfSsLugBGULFk5WzFH0A9qoEeulYCBONraVQS8WQuZoav6YQWG49TLeNBA8JqVsxUCF5mUPfy23MzcVtHAriLJCvyxj+cUksfh4op
